name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module_path:
        - https://github.com/anjuhubgit/iaccde.git/modules/vpc
        - https://github.com/anjuhubgit/iaccde.git/modules/ec2
        - https://github.com/anjuhubgit/iaccde.git/modules/secrets_manager
        - https://github.com/anjuhubgit/iaccde.git/modules/rds
        - https://github.com/anjuhubgit/iaccde.git/modules/s3
        - https://github.com/anjuhubgit/iaccde.git/modules/ecr
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your desired AWS region

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x.x # Specify your desired Terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
